export const mockData = {
  users: [
    {
      id: 1,
      role: 'admin',
      name: 'Super Admin',
      username: 'admin.demo',
    },
    {
      id: 2,
      role: 'staff',
      name: 'Rizal Pratama',
      username: 'staff.demo',
    },
    {
      id: 3,
      role: 'prajurit',
      name: 'Andi Saputra',
      username: 'prajurit.demo',
      nrp: '22104567',
      pangkat: 'Letda',
      kesatuan: 'Yonif 301',
      status: 'aktif',
    },
    {
      id: 4,
      role: 'prajurit',
      name: 'Bima Nugraha',
      username: 'bima.demo',
      nrp: '22104568',
      pangkat: 'Serda',
      kesatuan: 'Yonif 301',
      status: 'menunggu',
    },
  ],

  kategori: [
    { id: 1, nama: 'Senjata' },
    { id: 2, nama: 'Amunisi' },
    { id: 3, nama: 'Perlengkapan Lapangan' },
    { id: 4, nama: 'Komunikasi' },
  ],

  barang: [
    {
      id: 1,
      kode: 'BRG-0001',
      nama: 'Senapan Serbu 5.56 mm',
      kategoriId: 1,
      merk: 'Pindad',
      stokTotal: 24,
      stokTersedia: 18,
      satuan: 'Unit',
      kondisi: 'Baik',
      status: 'Tersedia',
      lokasi: 'Rak A-01',
      hargaPerolehan: 18500000,
    },
    {
      id: 2,
      kode: 'BRG-0002',
      nama: 'Pistol 9 mm',
      kategoriId: 1,
      merk: 'Pindad',
      stokTotal: 12,
      stokTersedia: 7,
      satuan: 'Unit',
      kondisi: 'Baik',
      status: 'Tersedia',
      lokasi: 'Rak A-02',
      hargaPerolehan: 9800000,
    },
    {
      id: 3,
      kode: 'BRG-0003',
      nama: 'Helm Tempur',
      kategoriId: 3,
      merk: 'Milday',
      stokTotal: 40,
      stokTersedia: 32,
      satuan: 'Unit',
      kondisi: 'Baik',
      status: 'Tersedia',
      lokasi: 'Rak B-01',
      hargaPerolehan: 1250000,
    },
    {
      id: 4,
      kode: 'BRG-0004',
      nama: 'Rompi Taktis',
      kategoriId: 3,
      merk: 'Defender',
      stokTotal: 28,
      stokTersedia: 0,
      satuan: 'Unit',
      kondisi: 'Baik',
      status: 'Dipinjam',
      lokasi: 'Rak B-02',
      hargaPerolehan: 2350000,
    },
    {
      id: 5,
      kode: 'BRG-0005',
      nama: 'Radio HT Lapangan',
      kategoriId: 4,
      merk: 'Motorola',
      stokTotal: 16,
      stokTersedia: 11,
      satuan: 'Unit',
      kondisi: 'Baik',
      status: 'Tersedia',
      lokasi: 'Rak C-01',
      hargaPerolehan: 4200000,
    },
    {
      id: 6,
      kode: 'BRG-0006',
      nama: 'Magazen 5.56 mm',
      kategoriId: 1,
      merk: 'Pindad',
      stokTotal: 60,
      stokTersedia: 0,
      satuan: 'Buah',
      kondisi: 'Baik',
      status: 'Dipinjam',
      lokasi: 'Rak A-03',
      hargaPerolehan: 185000,
    },
  ],

  peminjaman: [
    {
      id: 1,
      kode: 'PMJ-000001',
      prajuritId: 3,
      tanggalPinjam: '2026-09-12',
      tanggalKembaliRencana: '2026-09-18',
      tujuan: 'Latihan',
      status: 'menunggu',
      catatan: 'Latihan menembak rutin satuan.',
      details: [
        { barangId: 1, qty: 2 },
        { barangId: 3, qty: 2 },
      ],
      createdAt: '2026-09-11T08:30:00',
    },
    {
      id: 2,
      kode: 'PMJ-000002',
      prajuritId: 4,
      tanggalPinjam: '2026-09-10',
      tanggalKembaliRencana: '2026-09-16',
      tujuan: 'Operasi',
      status: 'dipinjam',
      catatan: 'Dukungan operasi pengamanan wilayah.',
      approvedBy: 'Rizal Pratama',
      approvedAt: '2026-09-09T14:10:00',
      details: [
        { barangId: 4, qty: 4 },
        { barangId: 6, qty: 12 },
      ],
      createdAt: '2026-09-09T10:15:00',
    },
    {
      id: 5,
      kode: 'PMJ-000005',
      prajuritId: 3,
      tanggalPinjam: '2026-09-15',
      tanggalKembaliRencana: '2026-09-17',
      tujuan: 'Pendidikan',
      status: 'disetujui',
      catatan: 'Simulasi penggunaan radio dalam pendidikan.',
      approvedBy: 'Super Admin',
      approvedAt: '2026-09-14T15:30:00',
      details: [
        { barangId: 5, qty: 2 },
      ],
      createdAt: '2026-09-14T12:00:00',
    },
    {
      id: 3,
      kode: 'PMJ-000003',
      prajuritId: 3,
      tanggalPinjam: '2026-08-21',
      tanggalKembaliRencana: '2026-08-25',
      tujuan: 'Pendidikan',
      status: 'selesai',
      catatan: 'Kegiatan pendidikan dasar.',
      approvedBy: 'Super Admin',
      approvedAt: '2026-08-20T09:00:00',
      returnedAt: '2026-08-25T16:20:00',
      details: [
        { barangId: 2, qty: 1 },
        { barangId: 5, qty: 1 },
      ],
      createdAt: '2026-08-19T13:45:00',
    },
    {
      id: 4,
      kode: 'PMJ-000004',
      prajuritId: 4,
      tanggalPinjam: '2026-08-15',
      tanggalKembaliRencana: '2026-08-17',
      tujuan: 'Lainnya',
      status: 'ditolak',
      catatan: 'Kegiatan di luar jadwal satuan.',
      approvedBy: 'Super Admin',
      approvedAt: '2026-08-14T11:30:00',
      details: [
        { barangId: 1, qty: 1 },
      ],
      createdAt: '2026-08-14T08:00:00',
    },
  ],

  activityLogs: [
    {
      id: 1,
      actor: 'Super Admin',
      role: 'admin',
      action: 'APPROVE',
      entity: 'PEMINJAMAN',
      description: 'Menyetujui PMJ-000002.',
      createdAt: '2026-09-09T14:10:00',
    },
    {
      id: 2,
      actor: 'Rizal Pratama',
      role: 'staff',
      action: 'BORROW',
      entity: 'PEMINJAMAN',
      description: 'Memproses PMJ-000002 menjadi dipinjam.',
      createdAt: '2026-09-10T07:45:00',
    },
    {
      id: 3,
      actor: 'Andi Saputra',
      role: 'prajurit',
      action: 'CREATE',
      entity: 'PEMINJAMAN',
      description: 'Membuat PMJ-000001.',
      createdAt: '2026-09-11T08:30:00',
    },
    {
      id: 4,
      actor: 'Super Admin',
      role: 'admin',
      action: 'RETURN',
      entity: 'PEMINJAMAN',
      description: 'Menyelesaikan PMJ-000003.',
      createdAt: '2026-08-25T16:20:00',
    },
  ],
};
